import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body clsassName={inter.className}>
        <Navbar></Navbar>
        {children}
        <Analytics></Analytics>
        <SpeedInsights></SpeedInsights>
        </body>
    </html>
  );
}
